# Minimal prep-only config (consumed by core.config.load_config(mode="prep"))

experiment:
  name: "sequence_fold_full"
  seed: 42
  union: "standard"   # must match a key under data.inputs

data:
  # Absolute paths only (no env indirection)
  experiments_root: "/mimer/NOBACKUP/groups/snic2022-22-552/filbern/fungal_classification/experiments"
  input_dir: "/mimer/NOBACKUP/groups/snic2022-22-552/filbern/fungal_classification/blast_filtered"
  filenames:
    prep_summary: "prep_summary.json"
  inputs:
    standard: ["a_original_sh_sequences", "b_recruited_99pct_species", "d_recruited_97pct_sp"]
    conservative: ["a_original_sh_sequences", "b_recruited_99pct_species", "c_recruited_99pct_sp"]

label_space:
  levels: ["phylum", "class", "order", "family", "genus", "species"]

prep:
  uppercase_sequences: true
  min_species_resolution: 4
  dedupe:
    scope: "within_species"
    keep_policy: "highest_resolution"
  folds:
    k: 10
    stratify_by: "species"
    seed: 42
  folds_species_group:
    k: 10
    stratify_by: "genus"
    seed: 42
  debug_subset:
    n_genera: 5
    min_species_per_genus: 2
    target_size: 10000
    seed: 42
